### ISSUE TITLE
CSS Bug - "Color" undefined leads to invisible text

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Talk#131]
One of our users ran into a bug where text that she typed into a field would appear white and thus invisible. She had a friend sleuth out the problem:

*The problem is that:
1. Yshish uses a white-on-black colour scheme in her OS and browser
2. the CSS sets "background-color" but it leaves "color" undefined (sort of)

More precisely:
1. application-$datetime.css sets "background-color" of <input> elements to #FFF. This is applied because the selector used is fairly specific.
2. application-$datetime.css doesn't set "color" for <input> elements; these just inherit "color" from their parent elements. Unfortunately, then the selector "input {...}" from resource://gre-resources/forms
.css takes over because it's more specific than the inherited "color" rule and it sets "color" to "-moz-FieldText". This is however "#fcfcfc" because Yshish uses a white-on-black colour scheme.

I therefore think that this is a bug in the Zooniverse CSS because it does explicitly set background colours for inputs but it effectively leaves the text colours at their default values -- which goes wrong whenever a user sets their default value to almost white. However, users should be able to change their colour schemes without having their websites break.*

Is this something we could fix? Thanks!

**Comment by chrissnyder** [comment]
Deploying a change for this now. Not really sure what's going on, so can't be sure it's fixed.

**Comment by DarrenMcRoy** [comment]
I'll ask!

**Comment by DarrenMcRoy** [comment]
Not fixed yet, apparently. 

![screen shot 2015-01-05 at 10 01 38 am](https://cloud.githubusercontent.com/assets/8987864/5615565/e8d33ce8-94c1-11e4-8641-2763d4c18a0d.png)

Dunno how much more time you want to devote to this, but I figured it might be possible to figure it out because of all that stuff that she had her friend sleuth out above?

**Comment by chrissnyder** [comment]
Shooting into the dark here, but how about niw?

**Comment by DarrenMcRoy** [comment]
I'll ask! :-)

**Comment by DarrenMcRoy** [comment]
This is fixed! Thank you, @chrissnyder!
