### ISSUE TITLE
"Zooniverse Team" title becomes just "Team" in PMs

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Talk#134]
Could I please get the full "Zooniverse Team" title for PMs? :-)

![imageedit_14_7568382326](https://cloud.githubusercontent.com/assets/8987864/5688197/32807d64-981a-11e4-9bed-9625b344e0e4.jpg)

Thanks!!

**Comment by aweiksnar** [comment]
@DarrenMcRoy I'd probably blur usernames on screenshots of PMs, since this repo is public

**Comment by DarrenMcRoy** [comment]
Oh, good call. One sec.
