### ISSUE TITLE
Tweet button from C&S object page has incorrect Twitter handle

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Talk#145]
If you click the Tweet button in the top right of the object page (e.g. http://talk.chimpandsee.org/#/subjects/ACP00036t8 ) you get this:

Some summary line http://talk.chimpandsee.org/#/subjects/ACP00036t8 via @chimp

It should be @chimpandsee , not @chimp ... can we fix?

**Comment by chrissnyder** [comment]
Alternative suggestion, we just use @the_zooniverse rather than @chimpandsee
