### ISSUE TITLE
Search button on the old Talks returns 502 errors, does nothing

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Talk#146]
I know that the search has never worked really well on the Talks that most of our projects are currently on, and we're not trying to fix that, but now the search button literally does *nothing*.

I know we don't have any time to spend on those old projects, let alone fixing that Search, but having it do nothing whatsoever seems to me to be seriously problematic, as the majority of our projects still live on that system.

@aweiksnar says it appears to be returning 502 errors -- @parrish ?

**Comment by parrish** [comment]
Fixed

**Comment by DarrenMcRoy** [comment]
Well that's a relief. Thank you!
