### ISSUE TITLE
Text overflow in Notifications section

### ISSUE THREAD

**Issue by Unskilled** [zooniverse/Talk#155]
When a user selects the font Courier New as part of their message, this apparently causes the text to overflow the div with class="unread notification" in the [Zooniverse Notifications](https://www.zooniverse.org/zooniverse/notifications) page.

Below is a screenshot of the affected area:
![zooniverse notifications panel overflow](https://cloud.githubusercontent.com/assets/759607/11879600/f97331dc-a4c1-11e5-8bd6-779c777f5bb6.PNG)

Notice the text overflowing past the right edge of the 'div' container.

The default font seems to be "Open Sans", and none of the notifications with this font specified overflow the container in the same way.

Here is the URL of the affected comment:
[Ask the Planet Four Researchers Anything!](https://www.zooniverse.org/talk/14/21101?comment=44804)

**Comment by parrish** [comment]
Hi!  This is actually a repository for an old version of Talk.  The new version is part of https://github.com/zooniverse/panoptes-front-end

Just trying to reproduce this now, but haven't been able to yet.  What browser/version are you using?

**Comment by Unskilled** [comment]
Thank you much!

I was using Firefox 42.0 on Windows 7 64-bit.
I do see the same thing today on version 43.0.1.

I apologize for not putting this in the correct place; I knew I had Panoptes bookmarked for a reason!

Also, you've helped me to realize the real underlying cause (I hope):
This issue seems to occur with text within a `<code>` tag.

<div class="markdown " data-reactid=".0.2.0.0.1.2.$63901.0.2"><p>Post body</p>
<pre><code>This text is allowed to overflow the box.</code></pre>
<p>Allan</p>
</div>

I see this issue with each of the following:
Internet Explorer 11.0.9600.18124 on Windows 7 64-bit 6.1.7601
Firefox 42.0 on Windows 7 64-bit 6.1.7601
Firefox 43.0.1 on Windows 7 64-bit 6.1.7601
IceWeasel 38.4.0 Debian Linux 3.16.0

Should I make a new post over at https://github.com/zooniverse/panoptes-front-end/issues ?
Thanks for your time!

**Comment by parrish** [comment]
No problem!

Yeah, it seems that for some reason the CSS rule for `white-space: pre-line` is not showing up on Windows.  I'll get a fix up shortly.

**Comment by parrish** [comment]
The fix should be live in ~20-30 minutes.  Thanks again for catching it!
