### ISSUE TITLE
profile image is giant on user profile on Ourboros Talk

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Talk#160]
@parrish not sure if I'm in the right place for this. When I went to my profile on Ouroboros Talk I noticed the profile picture has weird sizing issues see attached photo

<img width="1143" alt="screen shot 2016-09-20 at 8 27 12 am" src="https://cloud.githubusercontent.com/assets/753325/18670086/1435e724-7f0c-11e6-9c69-bc824275d23a.png">

**Comment by parrish** [comment]
Heh, yep, fix is on the way out.

**Comment by mschwamb** [comment]
Thanks.
