### ISSUE TITLE
Replacing Ouroboros projects breaks their Talk

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Talk#161]
It looks like when we replace an Ouroboros project with a Panoptes version it breaks the old Talk. See [https://talk.milkywayproject.org/](url).

**Comment by parrish** [comment]
Yep.  That's as expected.  I suppose you could archive the old one, but the new project will have a new talk.

**Comment by mrniaboc** [comment]
There are a few users requesting access to their old collections etc.

**Comment by parrish** [comment]
This will still let the site be accessible.  Login isn't shared with Panoptes anyway now.

**Comment by mrniaboc** [comment]
Nice work!

**Comment by mrniaboc** [comment]
@parrish Same issue now on talk.chicagowildlifewatch.org. Are you able to work your magic?

**Comment by astopy** [comment]
I've fixed that now (though it has the same issue with subject images as MWP which I'll fix shortly).
